### ISSUE TITLE
Replace `puppeteer` with `puppeteer-core`

### ISSUE THREAD

**Issue by ackava** [prasanaworld/puppeteer-screen-recorder#66]
** Feature Request

*Summary*
Ideally there would be no downside in building the package with `puppeteer-core`. However, user will have to install `puppeteer` manually. 

The problem lies in build scripts, for example, default cache folder are overwritten in AWS Lambda and it is not persisted. So we have to manually install puppeteer in different folder and disable default puppeteer download. But since this package directly adds `puppeteer` as dependency, installing this package removed manual default puppeteer location. So I have to manually uninstall, save default folder and reinstall. Have a look at this action yml, you will get the idea.

I am using `puppeteer.config.cjs` to force cache location to be `node_modules/puppeteer-chromium`.

```yml
    - run: npm ci
      # puppeteer-screen-recorder installs puppeteer by default, so we need to delete both
    - run: npm uninstall puppeteer puppeteer-screen-recorder
      # this will create fresh install in node_modules/puppeteer-chromium
    - run: npm install puppeteer
    - run: chmod -R +x node_modules/puppeteer-chromium
    # Since puppeteer-screen-recorder will delete cache folder we will save it in parent folder
    - run: mv node_modules/puppeteer-chromium puppeteer-chromium
    - run: npm install puppeteer-screen-recorder
    # Moving puppeteer-chromium back to default cache folder
    - run: mv puppeteer-chromium node_modules/puppeteer-chromium
```

If dependency is changed to `puppeteer-core` this problem will not occur.
